# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /usr/local/vitasdk/samples/hello_cpp_world

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /usr/local/vitasdk/samples/hello_cpp_world

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/vitasdk/samples/hello_cpp_world/CMakeFiles /usr/local/vitasdk/samples/hello_cpp_world//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /usr/local/vitasdk/samples/hello_cpp_world/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello_cpp_world.vpk

# Build rule for target.
hello_cpp_world.vpk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world.vpk
.PHONY : hello_cpp_world.vpk

# fast build rule for target.
hello_cpp_world.vpk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.vpk.dir/build.make CMakeFiles/hello_cpp_world.vpk.dir/build
.PHONY : hello_cpp_world.vpk/fast

#=============================================================================
# Target rules for targets named hello_cpp_world.self

# Build rule for target.
hello_cpp_world.self: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world.self
.PHONY : hello_cpp_world.self

# fast build rule for target.
hello_cpp_world.self/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.self.dir/build.make CMakeFiles/hello_cpp_world.self.dir/build
.PHONY : hello_cpp_world.self/fast

#=============================================================================
# Target rules for targets named hello_cpp_world

# Build rule for target.
hello_cpp_world: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hello_cpp_world
.PHONY : hello_cpp_world

# fast build rule for target.
hello_cpp_world/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/build
.PHONY : hello_cpp_world/fast

src/Objects/actor.obj: src/Objects/actor.cpp.obj

.PHONY : src/Objects/actor.obj

# target to build an object file
src/Objects/actor.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/actor.cpp.obj
.PHONY : src/Objects/actor.cpp.obj

src/Objects/actor.i: src/Objects/actor.cpp.i

.PHONY : src/Objects/actor.i

# target to preprocess a source file
src/Objects/actor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/actor.cpp.i
.PHONY : src/Objects/actor.cpp.i

src/Objects/actor.s: src/Objects/actor.cpp.s

.PHONY : src/Objects/actor.s

# target to generate assembly for a file
src/Objects/actor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/actor.cpp.s
.PHONY : src/Objects/actor.cpp.s

src/Objects/object.obj: src/Objects/object.cpp.obj

.PHONY : src/Objects/object.obj

# target to build an object file
src/Objects/object.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/object.cpp.obj
.PHONY : src/Objects/object.cpp.obj

src/Objects/object.i: src/Objects/object.cpp.i

.PHONY : src/Objects/object.i

# target to preprocess a source file
src/Objects/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/object.cpp.i
.PHONY : src/Objects/object.cpp.i

src/Objects/object.s: src/Objects/object.cpp.s

.PHONY : src/Objects/object.s

# target to generate assembly for a file
src/Objects/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Objects/object.cpp.s
.PHONY : src/Objects/object.cpp.s

src/Systems/Level/level.obj: src/Systems/Level/level.cpp.obj

.PHONY : src/Systems/Level/level.obj

# target to build an object file
src/Systems/Level/level.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Level/level.cpp.obj
.PHONY : src/Systems/Level/level.cpp.obj

src/Systems/Level/level.i: src/Systems/Level/level.cpp.i

.PHONY : src/Systems/Level/level.i

# target to preprocess a source file
src/Systems/Level/level.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Level/level.cpp.i
.PHONY : src/Systems/Level/level.cpp.i

src/Systems/Level/level.s: src/Systems/Level/level.cpp.s

.PHONY : src/Systems/Level/level.s

# target to generate assembly for a file
src/Systems/Level/level.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Level/level.cpp.s
.PHONY : src/Systems/Level/level.cpp.s

src/Systems/Render/render.obj: src/Systems/Render/render.cpp.obj

.PHONY : src/Systems/Render/render.obj

# target to build an object file
src/Systems/Render/render.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Render/render.cpp.obj
.PHONY : src/Systems/Render/render.cpp.obj

src/Systems/Render/render.i: src/Systems/Render/render.cpp.i

.PHONY : src/Systems/Render/render.i

# target to preprocess a source file
src/Systems/Render/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Render/render.cpp.i
.PHONY : src/Systems/Render/render.cpp.i

src/Systems/Render/render.s: src/Systems/Render/render.cpp.s

.PHONY : src/Systems/Render/render.s

# target to generate assembly for a file
src/Systems/Render/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Render/render.cpp.s
.PHONY : src/Systems/Render/render.cpp.s

src/Systems/Utils/config_parser.obj: src/Systems/Utils/config_parser.cpp.obj

.PHONY : src/Systems/Utils/config_parser.obj

# target to build an object file
src/Systems/Utils/config_parser.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/config_parser.cpp.obj
.PHONY : src/Systems/Utils/config_parser.cpp.obj

src/Systems/Utils/config_parser.i: src/Systems/Utils/config_parser.cpp.i

.PHONY : src/Systems/Utils/config_parser.i

# target to preprocess a source file
src/Systems/Utils/config_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/config_parser.cpp.i
.PHONY : src/Systems/Utils/config_parser.cpp.i

src/Systems/Utils/config_parser.s: src/Systems/Utils/config_parser.cpp.s

.PHONY : src/Systems/Utils/config_parser.s

# target to generate assembly for a file
src/Systems/Utils/config_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/config_parser.cpp.s
.PHONY : src/Systems/Utils/config_parser.cpp.s

src/Systems/Utils/vector.obj: src/Systems/Utils/vector.cpp.obj

.PHONY : src/Systems/Utils/vector.obj

# target to build an object file
src/Systems/Utils/vector.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/vector.cpp.obj
.PHONY : src/Systems/Utils/vector.cpp.obj

src/Systems/Utils/vector.i: src/Systems/Utils/vector.cpp.i

.PHONY : src/Systems/Utils/vector.i

# target to preprocess a source file
src/Systems/Utils/vector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/vector.cpp.i
.PHONY : src/Systems/Utils/vector.cpp.i

src/Systems/Utils/vector.s: src/Systems/Utils/vector.cpp.s

.PHONY : src/Systems/Utils/vector.s

# target to generate assembly for a file
src/Systems/Utils/vector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/Utils/vector.cpp.s
.PHONY : src/Systems/Utils/vector.cpp.s

src/Systems/controls.obj: src/Systems/controls.cpp.obj

.PHONY : src/Systems/controls.obj

# target to build an object file
src/Systems/controls.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/controls.cpp.obj
.PHONY : src/Systems/controls.cpp.obj

src/Systems/controls.i: src/Systems/controls.cpp.i

.PHONY : src/Systems/controls.i

# target to preprocess a source file
src/Systems/controls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/controls.cpp.i
.PHONY : src/Systems/controls.cpp.i

src/Systems/controls.s: src/Systems/controls.cpp.s

.PHONY : src/Systems/controls.s

# target to generate assembly for a file
src/Systems/controls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/Systems/controls.cpp.s
.PHONY : src/Systems/controls.cpp.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hello_cpp_world.dir/build.make CMakeFiles/hello_cpp_world.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... hello_cpp_world.self"
	@echo "... hello_cpp_world.vpk"
	@echo "... hello_cpp_world"
	@echo "... src/Objects/actor.obj"
	@echo "... src/Objects/actor.i"
	@echo "... src/Objects/actor.s"
	@echo "... src/Objects/object.obj"
	@echo "... src/Objects/object.i"
	@echo "... src/Objects/object.s"
	@echo "... src/Systems/Level/level.obj"
	@echo "... src/Systems/Level/level.i"
	@echo "... src/Systems/Level/level.s"
	@echo "... src/Systems/Render/render.obj"
	@echo "... src/Systems/Render/render.i"
	@echo "... src/Systems/Render/render.s"
	@echo "... src/Systems/Utils/config_parser.obj"
	@echo "... src/Systems/Utils/config_parser.i"
	@echo "... src/Systems/Utils/config_parser.s"
	@echo "... src/Systems/Utils/vector.obj"
	@echo "... src/Systems/Utils/vector.i"
	@echo "... src/Systems/Utils/vector.s"
	@echo "... src/Systems/controls.obj"
	@echo "... src/Systems/controls.i"
	@echo "... src/Systems/controls.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

